version: '2.3'
services:
  pfld-tf-gpu-2:
    stdin_open: true
    tty: true
    command: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: pfld-tf-gpu-2
    volumes:
      - ./:/usr/src/app
    #   - /data:/data
    #runtime: nvidia
    ports:
      - 10000:10000
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
