version: '2.3'
services:
  pfld-tf-gpu-1-14:
    stdin_open: true
    tty: true
    command: /bin/bash
    build: .
    container_name: pfld-tf-gpu-1-14
    volumes:
      - ./:/usr/src/app
      - /data:/data
    runtime: nvidia
    ports:
      - 9999:9999
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
